CREATE TABLE usuario (
	usuario_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	nome_completo varchar(45) NOT NULL,
	email varchar(45) NOT NULL
);

CREATE TABLE restaurante (
	restaurante_id INTEGER PRIMARY KEY,
	nome varchar(45) NOT NULL,
	comida_tipica varchar(45) NOT NULL,
	imagem varchar(45) NOT NULL,
	votos INTEGER NOT NULL
);

